"use client";
import { useEffect,useState } from "react";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Topbar from "@/components/Home/Topbar/Topbar";
import Footer from "@/components/Home/Footer/Footer";
import Header from "@/components/Home/Header/Header";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Samaro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isFixed, setIsFixed] = useState(false);


  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");

    const handleScroll = () => {
      const scrollTop = window.scrollY;
      setIsFixed(scrollTop > 2);
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <html lang="en">
    
      <head><link rel="icon" href="/favicon.ico" sizes="any" /></head>
      <body suppressHydrationWarning={true} className={inter.className}>
        <div className=""><Topbar />
        <div className="headerBottomspace" style={{
          position: 'fixed',
          top: isFixed ? 0 : '36px', 
          width: '100%',
        }}> 
          <Header />
        </div>
        
        </div>
       
        <div className="childrens_topPading pt-5 mt-4">{children}</div>
        <ToastContainer />

        <Footer />
      </body>
    </html>
  );
}
