
"use client";
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Topbar from "@/components/Home/Topbar/Topbar";
import Footer from "@/components/Home/Footer/Footer";
import Header from "@/components/Home/Header/Header";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useRouter } from "next/navigation";




const inter = Inter({ subsets: ["latin"] });



const metadata = {
  title: "Samaro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  let queryParams;

  // useEffect(() => {

  //     queryParams = window.location.pathname;
  //    console.log(queryParams)

  // }, [queryParams]);

  const [isAdmin, setIsAdmin] = useState(false)



  const [isFixed, setIsFixed] = useState(false);


  useEffect(() => {

    queryParams = window.location.pathname;
    if (queryParams.includes("admin")) {
      setIsAdmin(true)
    }
    // else{
    //   setIsAdmin(false)
    // }

    import("bootstrap/dist/js/bootstrap.bundle.min.js");

    const handleScroll = () => {
      const scrollTop = window.scrollY;
      setIsFixed(scrollTop > 2);
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (

    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <div className="">
          {!isAdmin && <Topbar />}

          <div className="headerBottomspace" style={{
            position: 'fixed',
            top: isFixed ? 0 : '36px',
            width: '100%',
          }}>
            {!isAdmin && <Header />}
          </div>
          <div className={`childrens_topPading ${isAdmin ? "pt-0 mt-0" : "pt-5 mt-4"} `}>{children}</div>
          <ToastContainer />
          {!isAdmin && <Footer />}
        </div>


      </body>
    </html>
  );
}
