
"use client";
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Topbar from "@/components/Home/Topbar/Topbar";
import Footer from "@/components/Home/Footer/Footer";
import Header from "@/components/Home/Header/Header";
import "./globals.css";
import dynamic from "next/dynamic";
import { BasicInfoProvider } from "@/components/BasicInfoContext";

const ToastContainer = dynamic(
  () => import("react-toastify").then((mod) => mod.ToastContainer),
  { ssr: false }
);

const inter = Inter({ subsets: ["latin"], display: "swap" });

const metadata = {
  title: "Samaro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let queryParams;
  const [isAdmin, setIsAdmin] = useState(false);
  const [isFixed, setIsFixed] = useState(false);

  useEffect(() => {
    queryParams = window.location.pathname;
    if (queryParams.includes("admin")) {
      setIsAdmin(true);
    }

    import("bootstrap/dist/js/bootstrap.bundle.min.js");
    import("@fortawesome/fontawesome-free/css/all.css");
    import("react-toastify/dist/ReactToastify.css");

    // Lenis smooth scrolling - dynamically imported
    let lenisInstance;
    import("lenis").then(({ default: Lenis }) => {
      import("lenis/dist/lenis.css");
      lenisInstance = new Lenis({
        duration: 1.2,
        easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
        smoothWheel: true,
      });

      function raf(time) {
        lenisInstance.raf(time);
        requestAnimationFrame(raf);
      }
      requestAnimationFrame(raf);
    });

    const handleScroll = () => {
      const scrollTop = window.scrollY;
      setIsFixed(scrollTop > 2);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });

    return () => {
      window.removeEventListener('scroll', handleScroll);
      if (lenisInstance) lenisInstance.destroy();
    };
  }, []);

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://graph.instagram.com" />
      </head>
      <body suppressHydrationWarning={true} className={inter.className}>
        <BasicInfoProvider>
          <div className="">
            {!isAdmin && <Topbar />}

            <div className="headerBottomspace" style={{
              position: 'fixed',
              top: isFixed ? 0 : '36px',
              width: '100%',
            }}>
              {!isAdmin && <Header />}
            </div>
            <div className={`childrens_topPading ${isAdmin ? "pt-0 mt-0" : "pt-5"} `}>{children}</div>
            <ToastContainer />
            {!isAdmin && <Footer />}
          </div>
        </BasicInfoProvider>
      </body>
    </html>
  );
}
